# Generated by Django 4.2 on 2023-06-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nupco_po', models.CharField(max_length=125)),
                ('customer_po', models.CharField(max_length=250)),
                ('locations', models.CharField(max_length=250)),
                ('issue_delivery', models.DateField()),
                ('PO_item_number', models.CharField(max_length=125)),
                ('nupco_Gen_code', models.CharField(max_length=125)),
                ('nupco_Trade_code', models.CharField(max_length=125)),
                ('desscription', models.CharField(max_length=125)),
                ('Ordeer_Qty', models.CharField(max_length=125)),
                ('available_Qty', models.CharField(max_length=125)),
                ('date_delivery', models.DateField()),
                ('creation_delivery', models.DateField()),
                ('status', models.CharField(max_length=250)),
            ],
        ),
    ]
