# Generated by Django 4.2 on 2023-06-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0002_ordeer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordeer',
            name='available_Qty',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='ordeer',
            name='creation_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordeer',
            name='date_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordeer',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
