# Generated by Django 4.2 on 2023-06-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0003_alter_ordeer_available_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordeer',
            name='available_Qty',
            field=models.IntegerField(blank=True, default=0, max_length=125, null=True),
        ),
    ]
