# Generated by Django 4.2 on 2023-06-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0004_alter_ordeer_available_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordeer',
            name='Requested_Qty',
            field=models.IntegerField(blank=True, default=0, max_length=125, null=True),
        ),
    ]
