# Generated by Django 4.2 on 2023-06-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0005_ordeer_requested_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordeer',
            name='Requested_Qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
