# Generated by Django 4.2 on 2023-06-16 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0007_alter_ordeer_available_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordeer',
            name='creation_delivery',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='ordeer',
            name='date_delivery',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='ordeer',
            name='status',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
